#!/bin/sh

echo "Installing Antidose"
go get
go install

# test if file exists
if [ ! -f $GOPATH/bin/gometalinter ]; then
  echo "Installing gometalinter"
  go get -u github.com/alecthomas/gometalinter
  $GOPATH/bin/gometalinter --install
fi
